name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker Image
      - name: Build Docker Image
        run: echo "buliding Dockerfile ..."
          

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 3: Deploy to the Frontend Server
      - name: Deploy to Frontend Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.FRONTEND_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            docker stop uptime-kuma || true
            docker rm uptime-kuma || true
            docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
